name: realdex_drill

task_name: drill

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    # point_cloud:
    #   shape: [512, 3]
    #   type: point_cloud
    img:
      shape: [3, 84, 84]
      type: img
    depth:
      shape: [1, 84, 84]
      type: depth
    agent_pos:
      shape: [24]
      type: low_dim
  action:
    shape: [28]

env_runner: null

dataset:
  _target_: diffusion_policy_3d.dataset.realdex_dataset.RealDexDataset
  zarr_path: data/realdex_drill.zarr
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  val_ratio: 0.02
  max_train_episodes: 90
